In [1]:
import torch

In [2]:
#############################################
a = torch.tensor([[2,4,6,8],[10,12,14,16]])
print(a.shape)
a

torch.Size([2, 4])


tensor([[ 2,  4,  6,  8],
        [10, 12, 14, 16]])

In [5]:
b = torch.tensor([[1,2,4,6]])
print(b.shape)
b

torch.Size([1, 4])


tensor([[1, 2, 4, 6]])

In [6]:
a/b

tensor([[ 2.0000,  2.0000,  1.5000,  1.3333],
        [10.0000,  6.0000,  3.5000,  2.6667]])

In [8]:
##################################################
a=(512,512)
a[:2]

(512, 512)

In [163]:
###################################################
a = torch.tensor([[[1,2,3],[5,6,7],[7,8,9],[10,11,12]],[[1,2,3],[5,6,7],[7,8,9],[10,11,12]]])
print(a.shape)
a

torch.Size([2, 4, 3])


tensor([[[ 1,  2,  3],
         [ 5,  6,  7],
         [ 7,  8,  9],
         [10, 11, 12]],

        [[ 1,  2,  3],
         [ 5,  6,  7],
         [ 7,  8,  9],
         [10, 11, 12]]])

In [164]:
b = torch.tensor([[[100],[10],[1],[0]],[[0],[1],[10],[100]]])
print(b.shape)
b

torch.Size([2, 4, 1])


tensor([[[100],
         [ 10],
         [  1],
         [  0]],

        [[  0],
         [  1],
         [ 10],
         [100]]])

In [165]:
print( (a*b).shape )
a*b

torch.Size([2, 4, 3])


tensor([[[ 100,  200,  300],
         [  50,   60,   70],
         [   7,    8,    9],
         [   0,    0,    0]],

        [[   0,    0,    0],
         [   5,    6,    7],
         [  70,   80,   90],
         [1000, 1100, 1200]]])

In [179]:
###########################################################
a = torch.tensor([[1,5,7,10],[11,55,77,100]])
print(a.shape)
a

torch.Size([2, 4])


tensor([[ 1,  5,  7, 10],
        [ 1,  5,  7, 10]])

In [180]:
b = torch.tensor([1,10,100,100])
print(b.shape)
b

torch.Size([4])


tensor([  1,  10, 100, 100])

In [182]:
print((b-a).shape)
b-a

torch.Size([2, 4])


tensor([[ 0,  5, 93, 90],
        [ 0,  5, 93, 90]])

In [205]:
###############################################################
a = torch.tensor([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2])
print(a.shape)
a

torch.Size([20])


tensor([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2])

In [212]:
b = torch.tensor([0, 0, 12, 13])
print(b.shape)
b

torch.Size([4])


tensor([ 0,  0, 12, 13])

In [213]:
print(b[a].shape)
b[a]

torch.Size([20])


tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 13, 13, 12, 12, 12, 12, 12, 12,
        12, 12])

In [34]:
############################################################
a = torch.tensor([[0.0099, 0.0237, 0.0059],
            [0.0085, 0.0307, 0.0093],
            [0.0082, 0.0362, 0.0101],
            [0.0085, 0.5307, 0.0093],
            [0.4082, 0.6362, 0.9101]])    
print(a.shape)
a

torch.Size([5, 3])


tensor([[0.0099, 0.0237, 0.0059],
        [0.0085, 0.0307, 0.0093],
        [0.0082, 0.0362, 0.0101],
        [0.0085, 0.5307, 0.0093],
        [0.4082, 0.6362, 0.9101]])

In [35]:
b = torch.tensor([0,1,2,3,4])
print(b.shape)
b

torch.Size([5])


tensor([0, 1, 2, 3, 4])

In [36]:
c = torch.tensor([0,0,0,1,2])
print(c.shape)
c

torch.Size([5])


tensor([0, 0, 0, 1, 2])

In [37]:
a[b, c]

tensor([0.0099, 0.0085, 0.0082, 0.5307, 0.9101])

In [256]:
###########################################################
a = torch.tensor([[[0.0099, 0.0237, 0.0059, 0.812],
            [0.0085, 0.0307, 0.0093, 0.245],
            [0.0082, 0.0362, 0.0101, 0.256],
            [0.0085, 0.5307, 0.0093, 0.345],
            [0.4082, 0.6362, 0.9101, 0.866]],
            
            [[0.0099, 0.0237, 0.0059, 0.256],
            [0.0085, 0.0307, 0.0093, 0.286],
            [0.0082, 0.0362, 0.0101, 0.247],
            [0.0085, 0.5307, 0.0093, 0.654],
            [0.4082, 0.6362, 0.9101, 0.758]],
                 
            [[0.0099, 0.0237, 0.0059, 0.485],
            [0.0085, 0.0307, 0.0093, 0.29],
            [0.0082, 0.0362, 0.0101, 0.95],
            [0.0085, 0.5307, 0.0093, 0.457],
            [0.4082, 0.6362, 0.9101, 0.222]]])    
print(a.shape)
a

torch.Size([3, 5, 4])


tensor([[[0.0099, 0.0237, 0.0059, 0.8120],
         [0.0085, 0.0307, 0.0093, 0.2450],
         [0.0082, 0.0362, 0.0101, 0.2560],
         [0.0085, 0.5307, 0.0093, 0.3450],
         [0.4082, 0.6362, 0.9101, 0.8660]],

        [[0.0099, 0.0237, 0.0059, 0.2560],
         [0.0085, 0.0307, 0.0093, 0.2860],
         [0.0082, 0.0362, 0.0101, 0.2470],
         [0.0085, 0.5307, 0.0093, 0.6540],
         [0.4082, 0.6362, 0.9101, 0.7580]],

        [[0.0099, 0.0237, 0.0059, 0.4850],
         [0.0085, 0.0307, 0.0093, 0.2900],
         [0.0082, 0.0362, 0.0101, 0.9500],
         [0.0085, 0.5307, 0.0093, 0.4570],
         [0.4082, 0.6362, 0.9101, 0.2220]]])

In [257]:
b = torch.tensor([0,2])
print(b.shape)
b

torch.Size([2])


tensor([0, 2])

In [258]:
c = torch.tensor([0,3])
print(c.shape)
c

torch.Size([2])


tensor([0, 3])

In [259]:
a[b, c] 
# both b and c should have same number of elements. if b is integer.
# "number of True in b" and c should have same number of elements. if b is bool.

tensor([[0.0099, 0.0237, 0.0059, 0.8120],
        [0.0085, 0.5307, 0.0093, 0.4570]])

In [310]:
####################################################################
a = torch.tensor([[-1,  2],
        [-1,  4],
        [ 2,  -2],
        [ 2,  -1]])
print(a.shape)
a

torch.Size([4, 2])


tensor([[-1,  2],
        [-1,  4],
        [ 2, -2],
        [ 2, -1]])

In [313]:
b = torch.tensor([[  42.,  1.],
        [  42.,  1.],
        [1., 207.],
        [1., 207.]])
print(b.shape)
b

torch.Size([4, 2])


tensor([[ 42.,   1.],
        [ 42.,   1.],
        [  1., 207.],
        [  1., 207.]])

In [314]:
torch.max(a,b)

tensor([[ 42.,   2.],
        [ 42.,   4.],
        [  2., 207.],
        [  2., 207.]])

In [332]:
################################################
a = torch.tensor([[-1,  2],
        [-1,  4],
        [ 2,  -2],
        [ 2,  -1]])
print(a.shape)
a = a[..., :, None, :2]
print(a.shape)
a

torch.Size([4, 2])
torch.Size([4, 1, 2])


tensor([[[-1,  2]],

        [[-1,  4]],

        [[ 2, -2]],

        [[ 2, -1]]])

In [336]:
b = torch.tensor([[  42.,  1.],
        [  42.,  1.],
        [1., 207.],
        [1., 207.]])
print(b.shape)
b = b[..., None, :, :2]
print(b.shape)
b

torch.Size([4, 2])
torch.Size([1, 4, 2])


tensor([[[ 42.,   1.],
         [ 42.,   1.],
         [  1., 207.],
         [  1., 207.]]])

In [337]:
c = torch.max(a, b)
print(c.shape)
c

torch.Size([4, 4, 2])


tensor([[[ 42.,   2.],
         [ 42.,   2.],
         [  1., 207.],
         [  1., 207.]],

        [[ 42.,   4.],
         [ 42.,   4.],
         [  1., 207.],
         [  1., 207.]],

        [[ 42.,   1.],
         [ 42.,   1.],
         [  2., 207.],
         [  2., 207.]],

        [[ 42.,   1.],
         [ 42.,   1.],
         [  2., 207.],
         [  2., 207.]]])

In [341]:
#######################################################
a = torch.tensor([[0.0099, 0.0237, 0.0059],
            [0.0185, 1.0307, 0.0093],
            [0.0082, 0.9362, 0.0101],
            [0.0785, 0.5307, 0.0093],
            [0.4082, 0.6362, 0.9101]]) 
print(a.shape)
a

torch.Size([5, 3])


tensor([[0.0099, 0.0237, 0.0059],
        [0.0185, 1.0307, 0.0093],
        [0.0082, 0.9362, 0.0101],
        [0.0785, 0.5307, 0.0093],
        [0.4082, 0.6362, 0.9101]])

In [342]:
torch.topk(a, 4, dim=0)

torch.return_types.topk(
values=tensor([[0.4082, 1.0307, 0.9101],
        [0.0785, 0.9362, 0.0101],
        [0.0185, 0.6362, 0.0093],
        [0.0099, 0.5307, 0.0093]]),
indices=tensor([[4, 1, 4],
        [3, 2, 2],
        [1, 4, 3],
        [0, 3, 1]]))

In [29]:
################################################################
x = torch.tensor([[True, True, False, True, True, True],
                [False, True, True, False, True, True]])
x.shape

torch.Size([2, 6])

In [30]:
a = x.unsqueeze(1)
print(a)
a.shape

tensor([[[ True,  True, False,  True,  True,  True]],

        [[False,  True,  True, False,  True,  True]]])


torch.Size([2, 1, 6])

In [31]:
b = a.permute(0,2,1)
print(b)
b.shape

tensor([[[ True],
         [ True],
         [False],
         [ True],
         [ True],
         [ True]],

        [[False],
         [ True],
         [ True],
         [False],
         [ True],
         [ True]]])


torch.Size([2, 6, 1])

In [32]:
print((a*b).shape)
a*b

torch.Size([2, 6, 6])


tensor([[[ True,  True, False,  True,  True,  True],
         [ True,  True, False,  True,  True,  True],
         [False, False, False, False, False, False],
         [ True,  True, False,  True,  True,  True],
         [ True,  True, False,  True,  True,  True],
         [ True,  True, False,  True,  True,  True]],

        [[False, False, False, False, False, False],
         [False,  True,  True, False,  True,  True],
         [False,  True,  True, False,  True,  True],
         [False, False, False, False, False, False],
         [False,  True,  True, False,  True,  True],
         [False,  True,  True, False,  True,  True]]])

In [41]:
##############################################################
x = torch.arange(16).view(4, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [42]:
torch.flip(x, [0])

tensor([[12, 13, 14, 15],
        [ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]])

In [8]:
#######################################################
x = torch.arange(32).view(2, 4, 4)
print(x.shape)
x

torch.Size([2, 4, 4])


tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31]]])

In [9]:
# replace all values for indices 1 and 2 (along dim=1) with 0.
x[:, [1,2]] = 0
x

tensor([[[ 0,  1,  2,  3],
         [ 0,  0,  0,  0],
         [ 0,  0,  0,  0],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [ 0,  0,  0,  0],
         [ 0,  0,  0,  0],
         [28, 29, 30, 31]]])